// types.ts
// NOTE: Merged content from types/socialAuth.ts and completed definitions to create a single source of truth for types.
export enum Page {
  Dashboard = 'Dashboard',
  Assets = 'Assets',
  ProFolio = 'ProFolio',
  WebDev = 'WebDev',
  Code = 'Code',
  Conceptualize = 'Conceptualize',
  Create = 'Create',
  Design = 'Design',
  Web3Tools = 'Web3Tools',
  SmartContractBuilder = 'SmartContractBuilder',
  PsychedelicNftWorkshop = 'PsychedelicNftWorkshop',
  PromptStudio = 'PromptStudio',
  BusinessMeeting = 'BusinessMeeting',
  Learning = 'Learning',
  Persona = 'Persona',
  Protocols = 'Protocols',
  AIStudio = 'AIStudio',
  Chat = 'Chat',
  Business = 'Business',
  Social = 'Social',
  Wallet = 'Wallet',
  Vault = 'Vault',
  Profile = 'Profile',
  Settings = 'Settings',
  ManageCategories = 'ManageCategories',
}

export type SocialPlatform =
  | 'instagram'
  | 'spotify'
  | 'youtube'
  | 'x'
  | 'website'
  | 'behance'
  | 'deviantart'
  | 'linkedin'
  | 'discord'
  | 'mirror'
  | 'opensea'
  | 'facebook'
  | 'github';

export interface SocialLink {
  platform: SocialPlatform;
  url: string;
}

export interface BrandAuthConfig {
  id: string;
  name: string;
  socials: SocialLink[];
}

export interface Asset {
  id: string;
  name: string;
  categoryId: string;
  value: number;
  quantity?: number;
  cryptoId?: string;
  description: string;
  imageUrl?: string;
  contractAddress?: string;
  tokenId?: string;
  tokenStandard?: string;
  blockchainNetwork?: string;
  address?: string;
  purchasePrice?: number;
  purchaseDate?: string;
  mintId?: string;
  mintTxHash?: string;
}

export interface CryptoCurrency {
  id: string;
  symbol: string;
  name: string;
  price: number;
  change24h: number;
  priceHistory: number[];
  isFavorite?: boolean;
}

export type VaultItemType = 'secret' | 'apiKey' | 'login';

export interface VaultItem {
  id: string;
  name: string;
  type: VaultItemType;
  encryptedContent: string;
  website?: string;
}

export interface Alert {
  id: string;
  cryptoId: string;
  target: number;
  direction: 'above' | 'below';
}

export interface Profile {
  name: string;
  bio?: string;
  website?: string;
  avatarUrl: string;
}

export interface AppSettings {
  defaultCurrency: 'USD' | 'EUR' | 'GBP' | 'JPY';
  notificationsEnabled: boolean;
}

export interface PortfolioHistoryPoint {
  timestamp: number;
  value: number;
}

export const cryptoAssetTypes = ['crypto'];
export const nftAssetTypes = ['nft-art', 'nft-collectible'];

export interface AssetCategory {
  id: string;
  name: string;
  group: string;
}

export type PositionCategory = 'Staking' | 'Yield Farming' | 'Lending' | 'Stocks' | 'Other';

export interface Position {
  id: string;
  name: string;
  category: PositionCategory;
  principal: number;
  apy: number;
  startDate: string;
  description?: string;
}

export interface Web3Wallet {
  address: string;
  balance: number;
  network: string;
}

export interface DeploymentTransaction {
  txHash: string;
  contractAddress: string;
  contractName: string;
  chainId: number;
  timestamp: number;
  abi: any[];
  signature: string;
}

// BiB! AI Types
export interface AITrait {
    name: string;
    value: number; // 0-100 scale
    description: string;
}

export type TraitCategory = 'ethics' | 'morals' | 'beliefs' | 'personality' | 'approach' | 'passions' | 'dreams' | 'dislikes' | 'plans' | 'knowledge';


export interface AIPersona {
    name: string;
    corePersona: string; // The uploaded initial persona
    traits: {
        ethics: AITrait[];
        morals: AITrait[];
        beliefs: AITrait[];
        personality: AITrait[];
        approach: AITrait[];
        passions: AITrait[];
        dreams: AITrait[];
        dislikes: AITrait[];
        plans: AITrait[];
        knowledge: AITrait[];
    };
    internalThoughts: string; // AI's latest thoughts
    realTimeLogic: string; // AI's reasoning for the last response
}

export interface AIProtocol {
    id: string;
    name: string;
    content: string;
    isActive: boolean;
}

export type AIMemoryItemType = 'file' | 'url' | 'text' | 'persona' | 'protocol';

export interface AIMemoryItem {
    id: string;
    type: AIMemoryItemType;
    name: string; // filename, url, or title
    contentSummary: string; // Summary generated by AI
    ingestedAt: number;
    source: string; // path or url
}

export interface ChatMessage {
    role: 'user' | 'model';
    content: string;
    imageUrl?: string;
    model?: 'Gemini' | 'OpenAI' | 'Anthropic';
}


export interface AppData {
  schemaVersion: number;
  assets: Asset[];
  cryptoCurrencies: CryptoCurrency[];
  vaultItems: VaultItem[];
  alerts: Alert[];
  profile: Profile;
  settings: AppSettings;
  socialAuth: BrandAuthConfig[];
  assetCategories: AssetCategory[];
  positions: Position[];
  web3Wallet: Web3Wallet | null;
  deploymentTransactions: DeploymentTransaction[];
  // BiB! AI State
  aiPersona: AIPersona;
  aiProtocols: AIProtocol[];
  aiMemory: AIMemoryItem[];
  chatHistory: ChatMessage[];
}

export interface EncryptedData {
  iv: string;
  salt: string;
  ciphertext: string;
}