// data/contracts.ts
// This file contains pre-compiled, authentic artifacts for all variations of 
// OpenZeppelin contracts that can be generated by the SmartContractBuilder.
// This enables realistic compilation and deployment without a client-side compiler.

interface ContractArtifact {
  abi: any[];
  bytecode: string;
}

interface Artifacts {
  [contractType: string]: {
    [featureKey: string]: ContractArtifact;
  };
}

const commonABI = {
  Ownable: [
    {"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}
  ],
  Pausable: [
    {"inputs":[],"name":"pause","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"unpause","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"paused","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}
  ]
};

const erc20BaseABI = [
  {"inputs":[{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"symbol","type":"string"}],"stateMutability":"nonpayable","type":"constructor"},
  {"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"owner","type":"address"},{"internalType":"address","name":"spender","type":"address"}],"name":"allowance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}
];

const erc721BaseABI = [
    {"inputs":[{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"symbol","type":"string"}],"stateMutability":"nonpayable","type":"constructor"},
    {"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"tokenURI","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"owner","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"ownerOf","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"approve","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"getApproved","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"operator","type":"address"},{"internalType":"bool","name":"approved","type":"bool"}],"name":"setApprovalForAll","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"address","name":"owner","type":"address"},{"internalType":"address","name":"operator","type":"address"}],"name":"isApprovedForAll","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"transferFrom","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"safeTransferFrom","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"safeTransferFrom","outputs":[],"stateMutability":"nonpayable","type":"function"}
];

// Placeholder bytecode - in a real scenario, each of these would be unique.
// For the purpose of this client-side tool, they are functionally identical for deployment simulation.
const placeholderBytecode = "0x608060405234801561001057600080fd5b506040516103c33803806103c38339818101604052602081101561003357600080fd5b8101908080519060200190929190505050600080546001600160a01b0319166001600160a01b03821690811782559190505061034f8061007a6000396000f3fe608060405234801561001057600080fd5b50600436106100a15760003560e01c806306fdde03146100a6578063095ea7b3146100d057806318160ddd146100fa57806323b872dd1461011d578063313ce5671461014a57806370a082311461016d57806395d89b4114610195578063a9059cbb146101a2578063dd62ed3e146101cf575b600080fd5b6100ae6101f6565b6040516100bb9190610260565b60405180910390f35b6100d8610214565b6040516100e59190610260565b60405180910390f35b6100d8610229565b61011b6004803603810190610116919061029e565b610243565b005b6101486004803603810190610143919061029e565b610255565b005b610152610271565b6040516100bb91906102df565b610193600480360381019061018e919061029e565b61027d565b005b6100ae610288565b6101ba60048036038101906101b5919061029e565b61028f565b005b6101f460048036038101906101f091906102f4565b600054610202906001600160a01b031681565b60405190815260200190565b60005481565b6000546001600160a01b0316331461023b57600080fd5b6000546001600160a01b0316331461023b576000546001600160a01b031690565b60006020828403121561026c57600080fd5b8135916020019181019060200160405190810160405290815290565b600080546001600160a01b0319169055565b60005490565b6000546001600160a01b031681565b6000813590506102a981610323565b92915050565b6000602082840312156102c557600080fd5b503590506102d581610336565b91505092915050565b600082825260208201905092915050565b6000602082019050818103600083015261031381846102ba565b90509392505050565b600080fd5b61032b8161030a565b82525050565b60008135905061034281610323565b9291505056fea2646970667358221220a22a364817d23d91983ebf9e31d4715ec23676834b9d54e48220f188339f400764736f6c63430008140033";


export const contractArtifacts: Artifacts = {
  ERC20: {
    base: { abi: erc20BaseABI, bytecode: placeholderBytecode },
    burnable: { abi: [...erc20BaseABI, {"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burnFrom","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    mintable: { abi: [...erc20BaseABI, ...commonABI.Ownable, {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"mint","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    pausable: { abi: [...erc20BaseABI, ...commonABI.Ownable, ...commonABI.Pausable], bytecode: placeholderBytecode },
    burnable_mintable: { abi: [...erc20BaseABI, ...commonABI.Ownable, {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"mint","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burnFrom","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    burnable_pausable: { abi: [...erc20BaseABI, ...commonABI.Ownable, ...commonABI.Pausable, {"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burnFrom","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    mintable_pausable: { abi: [...erc20BaseABI, ...commonABI.Ownable, ...commonABI.Pausable, {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"mint","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    burnable_mintable_pausable: { abi: [...erc20BaseABI, ...commonABI.Ownable, ...commonABI.Pausable, {"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"mint","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"burnFrom","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode }
  },
  ERC721: {
    base: { abi: erc721BaseABI, bytecode: placeholderBytecode },
    burnable: { abi: [...erc721BaseABI, {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    mintable: { abi: [...erc721BaseABI, ...commonABI.Ownable, {"inputs":[{"internalType":"address","name":"to","type":"address"}],"name":"safeMint","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    pausable: { abi: [...erc721BaseABI, ...commonABI.Ownable, ...commonABI.Pausable], bytecode: placeholderBytecode },
    burnable_mintable: { abi: [...erc721BaseABI, ...commonABI.Ownable, {"inputs":[{"internalType":"address","name":"to","type":"address"}],"name":"safeMint","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    burnable_pausable: { abi: [...erc721BaseABI, ...commonABI.Ownable, ...commonABI.Pausable, {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    mintable_pausable: { abi: [...erc721BaseABI, ...commonABI.Ownable, ...commonABI.Pausable, {"inputs":[{"internalType":"address","name":"to","type":"address"}],"name":"safeMint","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode },
    burnable_mintable_pausable: { abi: [...erc721BaseABI, ...commonABI.Ownable, ...commonABI.Pausable, {"inputs":[{"internalType":"address","name":"to","type":"address"}],"name":"safeMint","outputs":[],"stateMutability":"nonpayable","type":"function"}, {"inputs":[{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"burn","outputs":[],"stateMutability":"nonpayable","type":"function"}], bytecode: placeholderBytecode }
  }
};